/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'nibeuplink adapter settings': {
        en: 'Adapter settings for nibeuplink',
        de: 'Adaptereinstellungen für nibeuplink',
        ru: 'Настройки адаптера для nibeuplink',
        pt: 'Configurações do adaptador para nibeuplink',
        nl: 'Adapterinstellingen voor nibeuplink',
        fr: "Paramètres d'adaptateur pour nibeuplink",
        it: "Impostazioni dell'adattatore per nibeuplink",
        es: 'Ajustes del adaptador para nibeuplink',
        pl: 'Ustawienia adaptera dla nibeuplink',
        'zh-cn': 'template的适配器设置',
    },
    'Get it from https://api.nibeuplink.com/Applications.': {
        en: 'Get it from https://api.nibeuplink.com/Applications.',
        de: 'Gibts auf https://api.nibeuplink.com/Applications.',
        ru: 'Get it from https://api.nibeuplink.com/Applications.',
        pt: 'Get it from https://api.nibeuplink.com/Applications.',
        nl: 'Get it from https://api.nibeuplink.com/Applications.',
        fr: 'Get it from https://api.nibeuplink.com/Applications.',
        it: 'Get it from https://api.nibeuplink.com/Applications.',
        es: 'Get it from https://api.nibeuplink.com/Applications.',
        pl: 'Get it from https://api.nibeuplink.com/Applications.',
        'zh-cn': 'Get it from https://api.nibeuplink.com/Applications.',
    },
    'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html': {
        en: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        de: 'Muss nicht geändert werden. Es kann https://sebilm.github.io/ioBroker.nibeuplink/nibe.html verwendet werden.',
        ru: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        pt: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        nl: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        fr: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        it: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        es: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        pl: 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
        'zh-cn': 'Does not need to be changed. You can use https://sebilm.github.io/ioBroker.nibeuplink/nibe.html',
    },
    'Click here to generate the Auth Code on NIBE Uplink.': {
        en: 'Click here to generate the Auth Code on NIBE Uplink.',
        de: 'Hier klicken, um den Auth-Code auf NIBE Uplink zu generieren.',
        ru: 'Click here to generate the Auth Code on NIBE Uplink.',
        pt: 'Click here to generate the Auth Code on NIBE Uplink.',
        nl: 'Click here to generate the Auth Code on NIBE Uplink.',
        fr: 'Click here to generate the Auth Code on NIBE Uplink.',
        it: 'Click here to generate the Auth Code on NIBE Uplink.',
        es: 'Click here to generate the Auth Code on NIBE Uplink.',
        pl: 'Click here to generate the Auth Code on NIBE Uplink.',
        'zh-cn': 'Click here to generate the Auth Code on NIBE Uplink.',
    },
    'Paste your Auth Code here.': {
        en: 'Paste your Auth Code here.',
        de: 'Den Auth-Code hier einfügen.',
        ru: 'Paste your Auth Code here.',
        pt: 'Paste your Auth Code here.',
        nl: 'Paste your Auth Code here.',
        fr: 'Paste your Auth Code here.',
        it: 'Paste your Auth Code here.',
        es: 'Paste your Auth Code here.',
        pl: 'Paste your Auth Code here.',
        'zh-cn': 'Paste your Auth Code here.',
    },
    'Log in at https://www.nibeuplink.com. It is the number in the URL.': {
        en: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        de: 'Auf https://www.nibeuplink.com einloggen. Es ist die Zahl in der URL.',
        ru: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        pt: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        nl: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        fr: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        it: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        es: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        pl: 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
        'zh-cn': 'Log in at https://www.nibeuplink.com. It is the number in the URL.',
    },
    'Refresh interval': {
        en: 'Refresh interval',
        de: 'Wiederholungsintervall',
        ru: 'Refresh interval',
        pt: 'Refresh interval',
        nl: 'Refresh interval',
        fr: 'Refresh interval',
        it: 'Refresh interval',
        es: 'Refresh interval',
        pl: 'Refresh interval',
        'zh-cn': 'Refresh interval',
    },
    'Time in minutes of fetching data from Nibe Uplink.': {
        en: 'Time in minutes of fetching data from Nibe Uplink.',
        de: 'Aller wie viele Minuten die Daten von Nibe Uplink geholt werden.',
        ru: 'Time in minutes of fetching data from Nibe Uplink.',
        pt: 'Time in minutes of fetching data from Nibe Uplink.',
        nl: 'Time in minutes of fetching data from Nibe Uplink.',
        fr: 'Time in minutes of fetching data from Nibe Uplink.',
        it: 'Time in minutes of fetching data from Nibe Uplink.',
        es: 'Time in minutes of fetching data from Nibe Uplink.',
        pl: 'Time in minutes of fetching data from Nibe Uplink.',
        'zh-cn': 'Time in minutes of fetching data from Nibe Uplink.',
    },
    Language: {
        en: 'Language',
        de: 'Sprache',
        ru: 'Language',
        pt: 'Language',
        nl: 'Language',
        fr: 'Language',
        it: 'Language',
        es: 'Language',
        pl: 'Language',
        'zh-cn': 'Language',
    },
    'The language for naming the data objects.': {
        en: 'The language for naming the data objects.',
        de: 'Die Sprache, die verwendet wird, um die Datenobjekte zu benennen.',
        ru: 'The language for naming the data objects.',
        pt: 'The language for naming the data objects.',
        nl: 'The language for naming the data objects.',
        fr: 'The language for naming the data objects.',
        it: 'The language for naming the data objects.',
        es: 'The language for naming the data objects.',
        pl: 'The language for naming the data objects.',
        'zh-cn': 'The language for naming the data objects.',
    },
    'Manage heat pump (experimental)': {
        en: 'Manage heat pump (experimental)',
        de: 'Verwaltung der Wärmepumpe (experimentell)',
        ru: 'Manage heat pump (experimental)',
        pt: 'Manage heat pump (experimental)',
        nl: 'Manage heat pump (experimental)',
        fr: 'Manage heat pump (experimental)',
        it: 'Manage heat pump (experimental)',
        es: 'Manage heat pump (experimental)',
        pl: 'Manage heat pump (experimental)',
        'zh-cn': 'Manage heat pump (experimental)',
    },
    'Enable support for managing the heat pump': {
        en: 'Enable support for managing the heat pump',
        de: 'Unterstützung für die Verwaltung der Wärmepumpe aktivieren',
        ru: 'Enable support for managing the heat pump',
        pt: 'Enable support for managing the heat pump',
        nl: 'Enable support for managing the heat pump',
        fr: 'Enable support for managing the heat pump',
        it: 'Enable support for managing the heat pump',
        es: 'Enable support for managing the heat pump',
        pl: 'Enable support for managing the heat pump',
        'zh-cn': 'Enable support for managing the heat pump',
    },
    'You must pay for it on Nibe Uplink website. Use at your own risk!': {
        en: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        de: 'Man muss dafür auf der Nibe Uplink Website bezahlen. Verwendung auf eigene Gefahr!',
        ru: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        pt: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        nl: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        fr: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        it: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        es: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        pl: 'You must pay for it on Nibe Uplink website. Use at your own risk!',
        'zh-cn': 'You must pay for it on Nibe Uplink website. Use at your own risk!',
    },
    'Manage ID': {
        en: 'Manage ID',
        de: 'Verwaltungs-ID',
        ru: 'Manage ID',
        pt: 'Manage ID',
        nl: 'Manage ID',
        fr: 'Manage ID',
        it: 'Manage ID',
        es: 'Manage ID',
        pl: 'Manage ID',
        'zh-cn': 'Manage ID',
    },
    'The ID of the management sub-tree in Objects.': {
        en: 'The ID of the management sub-tree in Objects.',
        de: 'Die ID des Verwaltungsunterbaums im Objekte-Baum.',
        ru: 'The ID of the management sub-tree in Objects.',
        pt: 'The ID of the management sub-tree in Objects.',
        nl: 'The ID of the management sub-tree in Objects.',
        fr: 'The ID of the management sub-tree in Objects.',
        it: 'The ID of the management sub-tree in Objects.',
        es: 'The ID of the management sub-tree in Objects.',
        pl: 'The ID of the management sub-tree in Objects.',
        'zh-cn': 'The ID of the management sub-tree in Objects.',
    },
    'Manage Name': {
        en: 'Manage Name',
        de: 'Verwaltungsname',
        ru: 'Manage Name',
        pt: 'Manage Name',
        nl: 'Manage Name',
        fr: 'Manage Name',
        it: 'Manage Name',
        es: 'Manage Name',
        pl: 'Manage Name',
        'zh-cn': 'Manage Name',
    },
    'The name of the management sub-tree in Objects.': {
        en: 'The name of the management sub-tree in Objects.',
        de: 'Der Name des Verwaltungsunterbaums im Objekte-Baum.',
        ru: 'The name of the management sub-tree in Objects.',
        pt: 'The name of the management sub-tree in Objects.',
        nl: 'The name of the management sub-tree in Objects.',
        fr: 'The name of the management sub-tree in Objects.',
        it: 'The name of the management sub-tree in Objects.',
        es: 'The name of the management sub-tree in Objects.',
        pl: 'The name of the management sub-tree in Objects.',
        'zh-cn': 'The name of the management sub-tree in Objects.',
    },
    'Add a parameter': {
        en: 'Add a parameter',
        de: 'Parameter hinzufügen',
        ru: 'Add a parameter',
        pt: 'Add a parameter',
        nl: 'Add a parameter',
        fr: 'Add a parameter',
        it: 'Add a parameter',
        es: 'Add a parameter',
        pl: 'Add a parameter',
        'zh-cn': 'Add a parameter',
    },
    'Unit ID': {
        en: 'Unit ID',
        de: 'Unit ID',
        ru: 'Unit ID',
        pt: 'Unit ID',
        nl: 'Unit ID',
        fr: 'Unit ID',
        it: 'Unit ID',
        es: 'Unit ID',
        pl: 'Unit ID',
        'zh-cn': 'Unit ID',
    },
    Parameter: {
        en: 'Parameter',
        de: 'Parameter',
        ru: 'Parameter',
        pt: 'Parameter',
        nl: 'Parameter',
        fr: 'Parameter',
        it: 'Parameter',
        es: 'Parameter',
        pl: 'Parameter',
        'zh-cn': 'Parameter',
    },
    ID: {
        en: 'ID',
        de: 'ID',
        ru: 'ID',
        pt: 'ID',
        nl: 'ID',
        fr: 'ID',
        it: 'ID',
        es: 'ID',
        pl: 'ID',
        'zh-cn': 'ID',
    },
    Name: {
        en: 'Name',
        de: 'Name',
        ru: 'Name',
        pt: 'Name',
        nl: 'Name',
        fr: 'Name',
        it: 'Name',
        es: 'Name',
        pl: 'Name',
        'zh-cn': 'Name',
    },
    '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.': {
        en: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        de: '<b>Unit ID</b>: Die Unit in der Wärmepumpe. Meistens 0, manchmal höher.',
        ru: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        pt: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        nl: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        fr: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        it: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        es: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        pl: '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
        'zh-cn': '<b>Unit ID</b>: The unit within the heat pump. Mostly 0, sometimes higher.',
    },
    '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.': {
        en: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        de: '<b>Parameter</b>: Die Nummer des Parameters. Kann man im Internet für verschiedene Wärmepumpen finden. Zwischen 0 und 65535.',
        ru: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        pt: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        nl: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        fr: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        it: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        es: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        pl: '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
        'zh-cn': '<b>Parameter</b>: The number of the parameter. Can be found on the Internet for your heat pump. Between 0 and 65535.',
    },
    '<b>ID / Name</b>: The sub-ID / name in the Objects tree.': {
        en: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        de: '<b>ID / Name</b>: Die Sub-ID / der Name im Objekt-Baum.',
        ru: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        pt: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        nl: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        fr: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        it: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        es: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        pl: '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
        'zh-cn': '<b>ID / Name</b>: The sub-ID / name in the Objects tree.',
    },
};
